add kontilas dan efishery
devcbandung/awesome-communities-bdg pull request #4
Opened 2019-10-12 13:56 UTC by k1m0ch1

halo saya ingin mendaftarkan komunitas kontilas dan startup efishery

startup efishery udah minta ijin bang Anshori https://i.imgur.com/iJFijCG.png

(Tambahkan screenshot bukti izin jika diperlukan)

2019-10-12 15:13 UTC, koneko096 requested changes

2019-10-12 15:13 UTC, koneko096 commented on README.md
> +Tech Stack: NodeJS & MonggoDB \
```suggestion
Tech Stack: NodeJS & MongoDB \
```

2019-10-13 01:02 UTC, esafirm commented on README.md
> +Silakan [berkontribusi](CONTRIBUTING.md) dengan menambahkan startup lainnya!
Ini salah jadi duplicated Mas @k1m0ch1

2019-10-13 07:44 UTC, k1m0ch1 commented on README.md
> +Silakan [berkontribusi](CONTRIBUTING.md) dengan menambahkan startup lainnya!
duplicate bagian mana kah? @esafirm

2019-10-13 08:15 UTC, azaky requested changes
Thank you mas @k1m0ch1 kontribusinya! Tapi masih ada beberapa hal yang perlu diperbaiki, seperti pada komentar berikut.

2019-10-13 08:15 UTC, azaky commented on README.md
> +Silakan [berkontribusi](CONTRIBUTING.md) dengan menambahkan startup lainnya!
bagian `Silakan berkontribusi` ada di line 75 dan 78 mas. yg di line ini dihapus saja

2019-10-13 08:15 UTC, azaky commented on README.md
> +Narahubung: [Ahmad Zaky](https://www.facebook.com/azaky003) dan [Michaela Sandra](https://www.facebook.com/michaela.sandra.18) <br><br><br><br>
`<br>` nya tidak perlu sepertinya

```suggestion
Narahubung: [Ahmad Zaky](https://www.facebook.com/azaky003) dan [Michaela Sandra](https://www.facebook.com/michaela.sandra.18)
```

2019-10-13 08:15 UTC, azaky commented on README.md
> +Grup: masih kecil, kontak aja narahubung buat di invite, soon public
Kurang backslash `\` di akhir baris ini. Akibatnya baris `Narahubung` tidak muncul di baris baru

2019-10-13 08:51 UTC, k1m0ch1 commented on README.md
> +Narahubung: [Ahmad Zaky](https://www.facebook.com/azaky003) dan [Michaela Sandra](https://www.facebook.com/michaela.sandra.18) <br><br><br><br>
coba d  cek lagi bro, gw tambah <br> karena kalo ga pake hasilnya berantakan

2019-10-13 08:54 UTC, k1m0ch1 commented on README.md
> +Narahubung: [Ahmad Zaky](https://www.facebook.com/azaky003) dan [Michaela Sandra](https://www.facebook.com/michaela.sandra.18) <br><br><br><br>
![Screenshot_2019-10-13-15-53-24-654_com android chrome](https://user-images.githubusercontent.com/5756522/66713198-ae50f600-edd1-11e9-964b-ac233b19c53f.png)
ini kalo ga pake br

2019-10-13 08:54 UTC, k1m0ch1 commented on README.md
> +Grup: masih kecil, kontak aja narahubung buat di invite, soon public
done

2019-10-13 08:56 UTC, k1m0ch1 commented on README.md
> +Silakan [berkontribusi](CONTRIBUTING.md) dengan menambahkan startup lainnya!
done

2019-10-13 09:08 UTC, k1m0ch1 commented on README.md
> +Narahubung: [Ahmad Zaky](https://www.facebook.com/azaky003) dan [Michaela Sandra](https://www.facebook.com/michaela.sandra.18) <br><br><br><br>
lebih detailnya, ukuran gambar 168x168 iru kalo textnya cuman 5 baris ga akan muat, sedangkan di awesome speaker gambar 168x168 itu 7 baris text nya

2019-10-13 09:09 UTC, k1m0ch1 commented on README.md
> +Narahubung: [Ahmad Zaky](https://www.facebook.com/azaky003) dan [Michaela Sandra](https://www.facebook.com/michaela.sandra.18) <br><br><br><br>
monggo di cek lg @azaky

2019-10-13 09:39 UTC, azaky commented on README.md
> +Narahubung: [Ahmad Zaky](https://www.facebook.com/azaky003) dan [Michaela Sandra](https://www.facebook.com/michaela.sandra.18) <br><br><br><br>
wah iya ya hmm. soalnya tadi aku coba (di lokal sih) nggak  tapi kalau pake `<br>` akan beda2 untuk tiap entri dan tiap browser.

apa dipisah pakai `<hr>` aja ya antar entri? biar seragam

2019-10-13 10:01 UTC, k1m0ch1 commented on README.md
> +Narahubung: [Ahmad Zaky](https://www.facebook.com/azaky003) dan [Michaela Sandra](https://www.facebook.com/michaela.sandra.18) <br><br><br><br>
![image](https://user-images.githubusercontent.com/5756522/66713988-0f30fc00-eddb-11e9-92af-e9fe41b00ae1.png)
 ini kalo dipisah pake <hr>

saran gw sih lebih baik baris nya dijadiin 7, atau gw barusan tes pake image di scale jadi 136x136
@azaky

2019-10-13 10:13 UTC, k1m0ch1 commented on README.md
> +Narahubung: [Ahmad Zaky](https://www.facebook.com/azaky003) dan [Michaela Sandra](https://www.facebook.com/michaela.sandra.18) <br><br><br><br>
ato saran gw buat komunitas bisa tambahin beberapa baris, ya bisa ambil salah satu sih 👍 

- Basecamp
- Kumpul kumpul basecamp setiap 
- Group Telegram
- Group Whatsapp
- Official Site, kalo ada.
- Youtube Channel
- Motto

@azaky

2019-10-13 13:59 UTC, azaky commented on README.md
> +Narahubung: [Ahmad Zaky](https://www.facebook.com/azaky003) dan [Michaela Sandra](https://www.facebook.com/michaela.sandra.18) <br><br><br><br>
Maaf baru balas. Ah iya, tadi sepertinya saya coba pakai hr bisa, ternyata salah 😅 . Sepertinya lebih baik kalau ukuran gambarnya saja yang diperkecil. Saya ubah ukuran semua logo yang sudah ada ya, mungkin bisa disesuaikan.

Soal baris lain, sebenarnya aturan di contributing.md itu hanya saran sih, kalau ada info lain malah lebih baik lagi 👍 . Mungkin saya tambahkan penjelasannya di CONTRIBUTING.md ya

Thanks!

2019-10-14 06:07 UTC, k1m0ch1 commented on README.md
> +Narahubung: [Ahmad Zaky](https://www.facebook.com/azaky003) dan [Michaela Sandra](https://www.facebook.com/michaela.sandra.18) <br><br><br><br>
![image](https://user-images.githubusercontent.com/5756522/66731790-4a870580-ee83-11e9-8057-3f2866925212.png)
@azaky saran saya di 138px sih. soalnya di startup kan dia 6 baris, sedangkan komunitas 5 baris.

2019-10-14 06:12 UTC, k1m0ch1 commented on README.md
> +Narahubung: [Ahmad Zaky](https://www.facebook.com/azaky003) dan [Michaela Sandra](https://www.facebook.com/michaela.sandra.18) <br><br><br><br>
gw coba jadi 128px dl kalo gitu

2019-10-14 06:16 UTC, k1m0ch1 commented
@azaky udah semua ya, tolong di cek lagi.

2019-10-14 06:33 UTC, azaky approved these changes

2019-10-14 06:34 UTC, azaky commented
Thanks @k1m0ch1 ! merging ya

2019-10-14 06:34 UTC, merged