Add ADB
devcbandung/awesome-communities-bdg pull request #6
Opened 2019-10-13 01:24 UTC by esafirm

Halo, saya ingin menambahkan komunitas Android Developer Bandung ke daftar ini, dan saya sudah meminta izin kepada pihak yang terkait.

<img width="531" alt="Screen Shot 2019-10-13 at 08 17 07" src="https://user-images.githubusercontent.com/1691440/66709603-f2bca180-ed91-11e9-81ec-60d4d87d96bd.png">

2019-10-13 08:19 UTC, azaky requested changes
Terima kasih @esafirm kontribusinya! Tapi ada beberapa hal minor yang perlu diperbaiki seperti pada komentar.

2019-10-13 08:19 UTC, azaky commented on README.md
> +<br><br><br>
Ini tidak perlu. Karena ada `<img>` di bawah, pasti ada di baris baru juga

```suggestion
```

2019-10-13 08:19 UTC, azaky commented on README.md
> +<br><br>
Saya sarankan ubah ini ke `<hr/>`

```suggestion
<hr/>
```

2019-10-13 14:35 UTC, azaky commented on README.md
> +<br><br>
Seperti bahasan pada #4 lebih baik mengubah ukuran gambar saja

2019-10-13 14:37 UTC, azaky requested changes

2019-10-13 14:37 UTC, azaky commented on README.md
> +<img src="https://raw.githubusercontent.com/AndroidDeveloperBandung/meetup-cantik/master/adb_logo.jpeg" height="168px" width="168px" align="left" alt="" />
```suggestion
<img src="https://raw.githubusercontent.com/AndroidDeveloperBandung/meetup-cantik/master/adb_logo.jpeg" height="128px" width="128px" align="left" alt="" />
```

2019-10-15 03:39 UTC, esafirm commented
Fixed Mas @azaky tolong dicek lagi ya

2019-10-15 04:36 UTC, azaky approved these changes
Thanks @esafirm !

2019-10-15 04:36 UTC, merged